### ISSUE TITLE
Your keys are out in the open!

### ISSUE THREAD

**Issue by vaishnav-mk** [thelordzeus/assign-desk#6]
Saw your [linkedin post](https://www.linkedin.com/posts/arnavshukla_students-projects-reactjs-activity-7017457565055782912-Npzx) and decided to check out the code until I saw that your api keys were public [firebase data](https://github.com/thelordzeus/assign-desk/blob/main/src/firebase.js) - [message token](https://github.com/thelordzeus/assign-desk/blob/main/src/App.js#L19)
* consider using [ENVs](https://www.freecodecamp.org/news/heres-how-you-can-actually-use-node-environment-variables-8fdf98f53a0a) in the future to prevent misuse of such keys by bad actors in the future!

**Comment by thelordzeus** [comment]
Yeah thanks man they were out that time cause the env setup was not working. I fixed them immediately that time.
